name: Publish to GH Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Checkout destination
        uses: actions/checkout@v3
        if: github.ref == 'refs/heads/main'
        with:
          ref: gh-pages
          path: built-site

      - name: Setup Hugo
        run: |
          curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.129.0/hugo_0.129.0_linux-amd64.tar.gz'
          tar -zxvf /tmp/hugo.tar.gz -C ${RUNNER_TEMP}
          mv ${RUNNER_TEMP}/hugo /usr/local/bin/hugo

      - name: Build
        run: hugo

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          cp -Rf public/* ${GITHUB_WORKSPACE}/built-site/
          cd ${GITHUB_WORKSPACE}/built-site
          git add .
          git config user.name 'tyfnacici'
          git config user.email 'tyfnacici@gmail.com'
          git commit -m 'Updated site'
          git push

